services:
  hardware:
    build:
      context: .
      dockerfile: ./hils/core/hw/Dockerfile
    container_name: hilsim_hardware
    environment:
      - HW_TYPE=${HW_TYPE:-numeric}
      - ACT_HOST=0.0.0.0
      - ACT_PORT=${ACT_PORT:-5001}
      - STEP_MS=${STEP_MS:-10}
      - LOG_TIMESTAMP=${LOG_TIMESTAMP}
      - USER_ID=${UID:-1000}
      - GROUP_ID=${GID:-1000}
    networks: [ simnet ]
    cap_add:
      - NET_ADMIN  # tc コマンド用
    volumes:
      - ./logs:/app/logs

  simulator:
    build:
      context: .
      dockerfile: ./hils/core/sim/Dockerfile
    container_name: hilsim_simulator
    environment:
      - SIM_TYPE=${SIM_TYPE:-numeric}
      - ACT_HOST=${ACT_HOST:-hardware}
      - ACT_PORT=${ACT_PORT:-5001}
      - STEP_MS=${STEP_MS:-10}
      - REPLY_TIMEOUT_MS=${REPLY_TIMEOUT_MS:-2}
      - TOTAL_STEPS=${TOTAL_STEPS:-1000}
      - NETWORK_DELAY_MS=${NETWORK_DELAY_MS:-0}
      - NETWORK_DELAY_SIM_TO_HW_MS=${NETWORK_DELAY_SIM_TO_HW_MS:-0}
      - NETWORK_DELAY_HW_TO_SIM_MS=${NETWORK_DELAY_HW_TO_SIM_MS:-0}
      - LOG_TIMESTAMP=${LOG_TIMESTAMP}
      - USER_ID=${UID:-1000}
      - GROUP_ID=${GID:-1000}
    depends_on:
      - hardware
    networks: [ simnet ]
    cap_add:
      - NET_ADMIN  # tc コマンド用
    volumes:
      - ./logs:/app/logs

networks:
  simnet:
    driver: bridge